

trigger:
- none
pool:
  name: my-agent-pool

parameters:
- name: myname
  type: string
  default: name

- name: age
  type: string
  default: name

variables:
  greet: 'myname'
  age: 'age'

stages:
- stage: one_stage
  jobs:
  - job: one_job
    steps:
    - script: echo $(greet)

